### ISSUE TITLE
[FR] "Run all cells" command

### ISSUE THREAD

**Issue by cervera-queiroz** [twibiral/obsidian-execute-code#10]
Hi there,

Is there any possibility of running all code blocks using the command pallet at once? 

This would be great!

**Comment by twibiral** [comment]
Hello,
No that's not possible yet. It's only possible to execute single code blocks independent of each other.

Do you want to just run the code in each code block independently or do you want to execute them together as if they where subsequent parts of a single program?

I will add this to the list of features to implement.

**Comment by andrewcrook** [comment]
you would also need a way to pass data from one cell to another. I have seen this done of jupyter via a plugin called [SOS ](https://vatlab.github.io/sos-docs/) it had build in features to use a messaging queue (zeromq) and functions in languages to convert between different data types.
