### ISSUE TITLE
[BUG] Global injections issue with js notebook mode

### ISSUE THREAD

**Issue by milan338** [twibiral/obsidian-execute-code#109]
Setting the js global injects to `console.log('globally injected');` and trying to run `console.log('test')` gives strange output:

![image](https://user-images.githubusercontent.com/56327606/194733016-02cbe7a9-10c2-4be8-aba0-1775482e36a0.png)

When running this code block, the run button disappears, and only the clear button is there. The runtime has to be removed to be able to run it again.

**Comment by chlohal** [comment]
Thanks! :) I'm not certain, but I believe this was because of the extra newlines that the plugin inserts between the injects and the code block. Either way, fixed in #111 & improved stability so issues like this should be more difficult to fall into

**Comment by twibiral** [comment]
Resolved by #111 and released in [1.1.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.0.0)
