### ISSUE TITLE
[FR] TypeScript support

### ISSUE THREAD

**Issue by dsebastien** [twibiral/obsidian-execute-code#11]
It would be awesome to add support for the TypeScript programming language.

**Comment by twibiral** [comment]
ts-node looks very promising: https://stackoverflow.com/questions/39197034/how-do-i-run-typescript-files-directly-without-generating-any-javascript-files

**Comment by twibiral** [comment]
Released in [0.16.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/0.16.0)
