### ISSUE TITLE
Issue in running R from a note in Obsidian

### ISSUE THREAD

**Issue by ak45y** [twibiral/obsidian-execute-code#117]
Hi, 

Thanks for your work on this plugin. 

I am trying to run code chunks in R. I tried the following ways:

``{r}
	  print("abc")
``

`` r
	  print("abc")
``

Both give the following error message: 

<Error: spawn Rscript ENOENT>

Am I missing something basic?

**Comment by chlohal** [comment]
Hi! This appears to be an issue with your local installation of R: the issue indicates that the `spawn` call wasn't able to find Rscript. I can help you debug!

What operating system are you on?
If you're on Linux, have you installed Obsidian through Snap/Flatpak/AppImage? 
What version of the plugin are you using?

**Comment by arnabkdey** [comment]
Hi chlohal,

Thanks so much for helping me debug this. 

I am using Windows 11 and the plugin version is 1.0.0.

**Comment by chlohal** [comment]
Wonderful, thank you. If you open up a terminal (PowerShell or cmd) and enter in `Rscript`, what do you see?

**Comment by ak45y** [comment]
When I run RScript from C: It says: 

'Rscript' is not recognized as an internal or external command,
operable program or batch file.

But when I navigate to the bin folder to where R is installed for me, it says: 

<Usage: /path/to/Rscript [--options] [-e expr [-e expr2 ...] | file] [args]

--options accepted are
  --help              Print usage and exit
  --version           Print version and exit
  --verbose           Print information on progress
  --default-packages=list
                      Where 'list' is a comma-separated set
                        of package names, or 'NULL'
or options to R, in addition to --no-echo --no-restore, such as
  --save              Do save workspace at the end of the session
  --no-environ        Don't read the site and user environment files
  --no-site-file      Don't read the site-wide Rprofile
  --no-init-file      Don't read the user R profile
  --restore           Do restore previously saved objects at startup
  --vanilla           Combine --no-save, --no-restore, --no-site-file
                        --no-init-file and --no-environ

'file' may contain spaces but not shell metacharacters
Expressions (one or more '-e <expr>') may be used *instead* of 'file'
See also  ?Rscript  from within R>

By the way, my obsidian vault is in a google drive and my R is installed in my hard drive. Just in case this is helpful in debugging. 

Thanks for your help!

**Comment by twibiral** [comment]
Hi, looks like Rscript is not added to your PATH variable. You can try one of the following:

- Add the path to your R installation to your PATH variable.
- Go to the settings for this plugin in the Obsidian settings. There you change the path of Rscript from `Rscript` to `your/path/to/Rscript`

**Comment by ak45y** [comment]
That worked. Thanks so much for solving this!!
