### ISSUE TITLE
Rust Still Doesn't Run

### ISSUE THREAD

**Issue by mocktustudent** [twibiral/obsidian-execute-code#119]
You closed #81 but I don't think the issue has been addressed. Rust execution is still attempting to use cargo run to execute the Rust code block. cargo run can only execute rust code within a project with a configured Cargo.toml. My guess is that you should be attempting to use cargo eval since you're asking for that to be installed and that's the tool for executing rust scripts.

**Comment by isr413** [comment]
This is my normal account. The mockaccount is just a throw away for GitHub classroom.

**Comment by twibiral** [comment]
I was falsely assuming #81 was related to another bug. I reopened it and will close this instead. Thanks for the hint!
