### ISSUE TITLE
[BUG] Language selection dropdown resets on leaving settings

### ISSUE THREAD

**Issue by milan338** [twibiral/obsidian-execute-code#122]
This is pretty minor, but in the settings page, if you select a language other than javascript and leave the settings, when returning back to the settings, the settings of the previous language will be remembered, however the dropdown defaults back to Javascript:

![image](https://user-images.githubusercontent.com/56327606/195852505-c3c3ff72-1816-4fa9-9e82-832252c0c424.png)

**Comment by chlohal** [comment]
Just submitted a PR to fix this! Thanks for reporting :)
