### ISSUE TITLE
[BUG] Notebook mode with incorrect path incorrectly handled

### ISSUE THREAD

**Issue by milan338** [twibiral/obsidian-execute-code#125]
Right now, when the path to e.g. python is incorrectly set, when notebook mode is enabled, running a code block will show it as queued indefinitely with the indicator, and killing the runtime will make the block show the running indicator while doing nothing. It would be good to change this behaviour to show a notification instead that the process couldn't be spawned.

**Comment by chlohal** [comment]
Thank you, Milan! I've added a check & notification in #123 :)

**Comment by twibiral** [comment]
Closed by #123 I guess
