### ISSUE TITLE
Chinese characters printing bug

### ISSUE THREAD

**Issue by libenling** [twibiral/obsidian-execute-code#126]
when printing Chinese characters in Python, it  does not work right.
![uTools_1665833755840](https://user-images.githubusercontent.com/92899170/195984372-7758dc79-75f5-4baf-a73e-65c134eef17f.png)

**Comment by chlohal** [comment]
Hi! I can help. I have a few questions to assist in troubleshooting, if you don't mind. 

1. What version of Python are you using?
2. What OS are you on?
3. What version of Obsidian do you use?
4. Could you send a screenshot of the Python page of plugin settings?
5. How long have you had this issue?

**Comment by libenling** [comment]
Thank you for answering me so soon!

> What version of Python are you using?

Python 3.9.2
3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]

> What OS are you on?

Win10
Microsoft Windows [version 10.0.19044.2130]

> What version of Obsidian do you use?

1.0.0

> Could you send a screenshot of the Python page of plugin settings?

![uTools_1665836669983](https://user-images.githubusercontent.com/92899170/195986388-b83f544e-e719-4906-afe4-78b3fe5d32e7.png)

> How long have you had this issue?

2 days

**Comment by chlohal** [comment]
Thank you for the information! This is really helpful.

I believe I've found the issue: Python is outputting with your terminal's text encoding, but the plugin is interpreting it as UTF-8. If you insert this into your "inject Python code" block, it may fix the issue.

![image](https://user-images.githubusercontent.com/26300854/196003202-64a0c06b-a0d6-4096-9cb4-8d4c08834ba8.png)

![image](https://user-images.githubusercontent.com/26300854/196003212-09aa4637-80fb-4e3b-8bc4-fa1ff96f6e46.png)
(I confess that I wasn't able to find the same characters you used, so I only copied a random character from online. I hope that it works regardless-- if it doesn't, please let me know and I can assist more)

**Comment by libenling** [comment]
Thank you very much for helping me to solve this problem.
Your method did work.

![uTools_1665896231183](https://user-images.githubusercontent.com/92899170/196018849-66a959ac-9fcc-4741-be5f-0df5b0083939.png)

**Comment by chlohal** [comment]
Wonderful; thank you! Can this issue be closed?

**Comment by libenling** [comment]
Yes.

**Comment by qiaogaojian** [comment]
if above method doesn't work, try this: https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window
