### ISSUE TITLE
Didn't run R code block

### ISSUE THREAD

**Issue by iszhi** [twibiral/obsidian-execute-code#128]
Ater I specified the correct R exec path, I still cannot see the "run" button in the preview mode.

**Comment by chlohal** [comment]
Hi! I can assist you with your issue :) If you could you give some information on your system, to help troubleshoot, that would help a lot!

- OS & version
- Obsidian version
- Plugin version 
- Screenshot of your R language settings on the plugin's settings tab
- Screenshot of some markdown that can reproduce the problem, in edit mode

When you say "preview mode", do you mean live preview mode, or reading view?

**Comment by iszhi** [comment]
> Hi! I can assist you with your issue :) If you could you give some information on your system, to help troubleshoot, that would help a lot!
> 
> * OS & version
> * Obsidian version
> * Plugin version
> * Screenshot of your R language settings on the plugin's settings tab
> * Screenshot of some markdown that can reproduce the problem, in edit mode
> 
> When you say "preview mode", do you mean live preview mode, or reading view?

OS: Windows 10 Enterprise 21H2 19044.2006
Obsidian version: 1.0.0
Plugin version: 1.1.0

![image](https://user-images.githubusercontent.com/33443222/196031566-9e23cc74-69c6-43b6-8e57-9b44182da250.png)
![image](https://user-images.githubusercontent.com/33443222/196031596-50e6e51f-f531-4d15-a709-a172270aba82.png)

I mean reading view as you see in the screenshot

**Comment by chlohal** [comment]
I see, thanks! Could you try using a lowercase `r` for the language label? This fixed it for me.

````
```r
a <- c(1,2,3)
print(a)
```
````
I will code a fix so that you and other R users won't have to use this workaround in the next release. Thank you for working with me to fix the issue!

**Comment by iszhi** [comment]
> I see, thanks! Could you try using a lowercase `r` for the language label? This fixed it for me.
> 
> ```
> ```r
> a <- c(1,2,3)
> print(a)
> ```
> ```
> 
> It seems like this is the intended behaviour of Obsidian; if this is acceptable to you, please feel free to close the issue. If not, I can code a fix so that you and other R users may use a capital R in the next release. Thank you for working with me to fix the issue!

Great. lowercase `r` also resloved my problem. Thanks for your effort.
