### ISSUE TITLE
Problem in running codes in R

### ISSUE THREAD

**Issue by ak45y** [twibiral/obsidian-execute-code#132]
Hi,

I am having trouble executing simple functions in R. For example:

I first create a simple dataframe as such:

`df <- data.frame(
	a = c(1:10),
	b = rep(c(0:1), 5),
	c = c(11:20)
)`

When I run this, the plug-in shows a pop-up saying **Done!** However, when I try to use the dataframe it throws errors:

`head(df)`

gives the following error:

`function (x, df1, df2, ncp, log = FALSE)    
 {                                           
     if (missing(ncp))                       
         .Call(C_df, x, df1, df2, log)       
     else .Call(C_dnf, x, df1, df2, ncp, log)
} `

and

`mean(df$a)`

gives the following error:

 `Error in df$a : object of type 'closure' is not subsettable
Calls: mean
Execution halted`

I would really appreciate any help in resolving this.

Thank you.

**Comment by chlohal** [comment]
Hi! I think I may know the problem: are the first and second statements in different code blocks?

**Comment by ak45y** [comment]
You are right - using the variables in the same code block solves the problem. 

It would be great if the Notebook mode is available for R as well. 

Thanks so much and good luck with mid-terms!!

**Comment by chlohal** [comment]
Heyo! I wanted to let you know that I finished & submitted a PR. The feature should be available in master pretty soon (assuming I haven't made any glaring errors with the implementation!)
