### ISSUE TITLE
WSL2 Support on Windows 10/11

### ISSUE THREAD

**Issue by ilkersigirci** [twibiral/obsidian-execute-code#133]
I am on windows 11 with wsl2 installed. But I couldn't find a way to enter python path which is within wsl2. Will there be any support for wsl2? Thanks.

Things I have tried and failed as pythonpath in plugin settings:
- \\wsl\Ubuntu/usr/bin/python3
- wsl ~ -e sh -c "python3"
- wsl -e python3

Btw I can succesfully invoke python if I run with powershell code block as the following within md file

```powershell
wsl ~ -e python3 -c "import uuid; print(uuid.uuid4().hex)"
```

which prints out as expected:  ad6ee6b418c849a499f2971a5d86cb53

Obsidian version: 1.0.0
Plugin version: 1.1.1

**Comment by chlohal** [comment]
Wonderful; thank you!

I think that the issue is that you're putting `wsl -e python3` in the python *path*. The path should resolve to 1 binary. Could you try putting `wsl` in the path, and `-e python3` in the arguments?

**Comment by ilkersigirci** [comment]
Thanks for fast response, unfortunately, your method didn't work.

**Comment by chlohal** [comment]
Are you using Notebook Mode?

**Comment by ilkersigirci** [comment]
Just upgraded the plugin to 1.2.0. Enabling/Disabling notebook mode didn't affect anything :(

**Comment by ilkersigirci** [comment]
Little success update:


I have created `/home/test.py` file inside wsl2.

```python
# Code in /home/test.py

print("TEST")
```

- Notebook mode disabled
- Python path: wsl
- Python arguments: -e python3 /home/test.py


When I configured like above and run a python code block in md file, it successfully runs the content inside `home/test.py` file.
But unfortunately the codeblock inside md file doesn't run

**Comment by chlohal** [comment]
Interesting! The plugin does insert the file after your arguments, but it seems like because you're on windows, the plugin is inserting the windows path (`C:\Users\...`) instead of the corresponding WSL path (`/mnt/c/Users/...`).

I think that WSL support will need a setting on the plugin's side.

**Comment by ilkersigirci** [comment]
> Interesting! The plugin does insert the file after your arguments, but it seems like because you're on windows, the plugin is inserting the windows path (`C:\Users\...`) instead of the corresponding WSL path (`/mnt/c/Users/...`).
> 
> I think that WSL support will need a setting on the plugin's side. 
> 
> 

Makes sense. A path mapping needed if user provide Wsl as python path .Btw, I can be your tester  while you are develeping this feature if you don't have access to any Wsl2 supported machine.

**Comment by chlohal** [comment]
Thanks! I have just made a PR for WSL support-- it works on my machine, but I _just_ installed WSL (and I'm not quite sure that I did the install properly ,--,), so I'm not sure if there'd be differences on other computers! If you could test, that would be great! :)

Here are the settings I used:

![image](https://user-images.githubusercontent.com/26300854/196824414-a0b1a712-6577-47e5-b421-162321cab230.png)

**Comment by ilkersigirci** [comment]
I have tested your version. It works wonderfully. Thank you.

**Comment by chlohal** [comment]
Huzzah, thanks! Currently, I only added it to basic mode because PR #140 is a rather large refactoring of notebook mode, but as soon as #140 gets merged, I'll add it to notebook too.

**Comment by daniel347x-cs** [comment]
Doesn't work for C++ with Cling (in WSL).
