### ISSUE TITLE
Scala Language Support

### ISSUE THREAD

**Issue by xiligey** [twibiral/obsidian-execute-code#134]
It will be so nice if this plugin support scala language:)

**Comment by chlohal** [comment]
Coded & submitted in PR #135! Assuming I didn't make any glaring errors in the implementation (fingers crossed!), you can expect the feature to land in roughly a week or two at most :)

**Comment by twibiral** [comment]
Released in version 1.2.0

**Comment by xiligey** [comment]
> Coded & submitted in PR #135! Assuming I didn't make any glaring errors in the implementation (fingers crossed!), you can expect the feature to land in about a week or two (no promises on that though).
> 
> Outdated; this was released in 1.2.0

Nice work, thanks.
