### ISSUE TITLE
[BUG] Killing a runtime leaves queued blocks unrunnable

### ISSUE THREAD

**Issue by milan338** [twibiral/obsidian-execute-code#136]
When using an interactive runner like python, killing the runtime while blocks are queued will correctly kill the currently running block, however if there are other blocks queued (like waiting for `time.sleep(100)`), all the queued blocks will show the 'block running' indicator indefinitely, and the run code button will not show up.

**Comment by chlohal** [comment]
This is odd, and almost certainly a regression, since this was one of the cases I specifically tested when developing the feature. I'll look into this later, but I have midterms at the moment so I'm a bit swamped; sorry!

**Comment by chlohal** [comment]
Did this happen since #138 or is it new?

**Comment by milan338** [comment]
It happens on the current main branch.

**Comment by chlohal** [comment]
Gotcha, thanks. I think I found the issue & I just made a PR-- does #139 fix the problem on your machine?

**Comment by chlohal** [comment]
Can this be closed? (sorry)

**Comment by milan338** [comment]
Thanks for the fix, works on my end. I think this can be closed.
