### ISSUE TITLE
Python cant find '__main__' module 

### ISSUE THREAD

**Issue by Jimsan123** [twibiral/obsidian-execute-code#137]
When i execute any code block, e.g.,
```python
print("hello")
```
i get the following error: 
```
/usr/bin/python3: can't find '__main__' module in '/home/user/'
```
The Python path is set to `/usr/bin/python3` as it is where python is installed for me
Os is Ubuntu 22.04 and Obsidian was installed through a .deb package 
Obsidian version 1.0.0
Execute Code version 1.1.0

**Comment by twibiral** [comment]
This is strange and shouldn't happen as python doesn't need a __main__ module.

Try adding changing your snippet to:

```python
if __name__ == "__main__":
    print("hello")
```

Are you using the notebook mode for python? If yes, try switching to the normal mode.

**Comment by Jimsan123** [comment]
I tried running the code and it returned the same error. 

```python
if __name__ == "__main__":
    print("hello")
```
Then i turned ON Notebook mode and then i got this error. 
```python
    return _get_module_details(main_name)
  File "/usr/lib/python3.10/runpy.py", line 140, in _get_module_details
    raise error("No module named %s" % mod_name)
ImportError: No module named __main__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 189, in _run_module_as_main
    mod_name, mod_spec, code = _get_main_module_details(_Error)
  File "/usr/lib/python3.10/runpy.py", line 241, in _get_main_module_details
    raise error("can't find %r module in %r" %
runpy._Error: can't find '__main__' module in '/home/user/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 192, in _run_module_as_main
    sys.exit(msg)
SystemExit: /usr/bin/python3: can't find '__main__' module in '/home/user/'
hello
```
So i finally manages to print hello but with some errors :D 
(my user dir is changed to "user" to cover sensitive info)

**Comment by Jimsan123** [comment]
I just ran the same code after a while, and it all seems to works now... thanks :100:

**Comment by chlohal** [comment]
I'm glad your problem was fixed :)
For future reference purposes, did you do anything specific to fix it?

**Comment by Jimsan123** [comment]
Nope, I wish I did. I just ran the code again and it worked... sry :D
