### ISSUE TITLE
Loading status does not disappear after running

### ISSUE THREAD

**Issue by ZackYJz** [twibiral/obsidian-execute-code#150]
After running, there is a loading circle in the upper left corner, which cannot be clicked and will not disappear. I'm not sure what caused it.
<img width="621" alt="image" src="https://user-images.githubusercontent.com/58540119/197328409-0998ed0a-c454-4721-a361-9e55273efb30.png">

**Comment by chlohal** [comment]
Do you have any other plugins or themes installed? One of them could be conflicting with the loading indicator. If you would feel comfortable sending a list, I can look into it and code a fix :)

**Comment by ZackYJz** [comment]
Thank you for reply. I tried, it turned out to be the theme "Blue Topaz"

**Comment by ZackYJz** [comment]
> Do you have any other plugins or themes installed? One of them could be conflicting with the loading indicator. If you would feel comfortable sending a list, I can look into it and code a fix :)

Thank you for reply. I tried, it turned out to be the theme "Blue Topaz"

**Comment by ZackYJz** [comment]
> Do you have any other plugins or themes installed? One of them could be conflicting with the loading indicator. If you would feel comfortable sending a list, I can look into it and code a fix :)

I solved this conflict by writing a  CSS snippet. Another problem：
Even if it's running normally, an "Error"  will also pop up. Is there a problem with the logic in the following pictrue?
<img width="504" alt="image" src="https://user-images.githubusercontent.com/58540119/197508892-e9289317-a6d5-4974-aa78-0badd86eeb6b.png">

**Comment by chlohal** [comment]
> Another problem： Even if it's running normally, an "Error" will also pop up. Is there a problem with the logic in the following pictrue? <img alt="image" width="504" src="https://user-images.githubusercontent.com/58540119/197508892-e9289317-a6d5-4974-aa78-0badd86eeb6b.png">

Yep! Thanks-- this error is fixed on the `develop` branch (see #144 ), so it should disappear in the next release. Thank you :)

**Comment by chlohal** [comment]
Thank you for the CSS! If you don't mind my asking, do you know how it works/what the diff is? If so, then you could open a PR to make sure it works with all themes :)

**Comment by mayurankv** [comment]
Also have this issue with minimal theme and no other codeblock appearance affecting plugins I know of (though quite a few in general). Will try out the css and see if that helps

**Comment by chlohal** [comment]
Hmm, ok. I'm going to try a few things & see if we can make it play well with all themes. Thanks for reporting!
