### ISSUE TITLE
have trouble running mathematica

### ISSUE THREAD

**Issue by Y-S-A** [twibiral/obsidian-execute-code#151]
My wolfram works well in terminal, but when i press the button to run in obsidian, there is no reaction. And I can't find any issue that report this. So I post this to inquire.
<img width="432" alt="image" src="https://user-images.githubusercontent.com/93212117/197333438-dedde800-48bf-498f-a694-1009a5335aae.png">
<img width="489" alt="image" src="https://user-images.githubusercontent.com/93212117/197333515-cdc66b43-e911-4862-af20-28e4baac2bb3.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/93212117/197333532-ab1c9ce7-7930-4b22-ad86-d35556109e2c.png">
<img width="532" alt="image" src="https://user-images.githubusercontent.com/93212117/197333599-58117fc2-e489-4251-a70b-60bbb6809f38.png">
Also, I have noticed that it seems that the setting for mathematica was connected to setting of kotlin. By which i mean, when you change the path of Kotlin, the path of mathematica will also change. It seems a bug. 
<img width="545" alt="image" src="https://user-images.githubusercontent.com/93212117/197333681-1faea6ed-0936-41f0-8cf3-ccd85ac742f3.png">
<img width="540" alt="image" src="https://user-images.githubusercontent.com/93212117/197333691-5600c60f-0c03-4bec-8ea3-cfb38035c8cd.png">

**Comment by chlohal** [comment]
Hi! Yep, I see that bug too. I've made a hotfix for the issue; thank you very much for reporting it!

Could you try running your script in a file? If you put your script in `file.wls` and run `wolframscript file.wls`, then it will replicate what the plugin does more closely.

**Comment by chlohal** [comment]
Partially fixed in #152

**Comment by twibiral** [comment]
#151 is released in [1.3.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.3.0). I think we can close this issue?

**Comment by Y-S-A** [comment]
Thank you very much for fixing this!

**Comment by twibiral** [comment]
You're welcome.
