### ISSUE TITLE
Support both Windows and Mac system

### ISSUE THREAD

**Issue by xiligey** [twibiral/obsidian-execute-code#156]
I want to use this plugin on both  my window10 and mac, and I use git to sync. But when I run python code on Win10, I set python path as "D:\Python3\python.exe", and it will sycn to my mac, so it failed to run python code on Mac.

I hope that this plugin can support multi system, for example:

Python path mac: /Users/jack/python3/python
Python path win10: D:\Python3\python.exe

**Comment by chlohal** [comment]
Do you have `python` added to your PATH variable on both systems? If yes, you should be able to write "`python`" in the path & it will work.

**Comment by xiligey** [comment]
> Do you have `python` added to your PATH variable on both systems? If yes, you should be able to write "`python`" in the path & it will work.

Thanks, it works.
