### ISSUE TITLE
I'm working on a PR for Zig : How Do I test ?!!!

### ISSUE THREAD

**Issue by alfu32** [twibiral/obsidian-execute-code#170]
Problem : how do I test the developments?

I thought that building and installing into an obsidian vault should do it.
Doing a npm run build does not give me an artefact.

What am I missing here ?

thank you

**Comment by alfu32** [comment]
I managed to find the compiled main.js and copy it to the vault

**Comment by twibiral** [comment]
The only way to test is by compiling it and executing it on your own device. We plan to integrate automatic tests sometime down the wrote (see #121 )
