### ISSUE TITLE
[BUG] R uses an entire CPU core, even when Obsidian is closed

### ISSUE THREAD

**Issue by sandalbanditten** [twibiral/obsidian-execute-code#172]
![image](https://user-images.githubusercontent.com/45170745/201424884-034b0393-020c-4d7f-a1a4-29a1124e1830.png)
In the picture above, the plugin has run three R-scripts, and then Obsidian has been closed, but an entire core continues to be used by each script.

**Comment by chlohal** [comment]
This should have been fixed by #139; it seems like the fix wasn't as functional as expected.

What OS are you on?
What version of the plugin are you using?
Could you send a screenshot of your plugin settings?

**Comment by sandalbanditten** [comment]
I am on arch linux, x86.
I am using version 1.4.0.
Here are my settings:
![image](https://user-images.githubusercontent.com/45170745/201497930-083ba0a8-1edf-4aaa-b6f1-401e5639c8d6.png)

**Comment by chlohal** [comment]
Thank you! 

Do you have the `pkill` command available? I'm sorry: I'm not familiar with Arch, so I don't want to assume.

**Comment by sandalbanditten** [comment]
It is avaible, and it is the way I kill the process afterwards.

**Comment by chlohal** [comment]
I understand, thanks. Do you use SIGTERM or SIGKILL?

**Comment by sandalbanditten** [comment]
The issue seems to have been fixed in the latest version of the plugin.
I used SIGKILL when the problem still was around.

**Comment by chlohal** [comment]
Understood, thanks! May the issue be closed?

**Comment by sandalbanditten** [comment]
Yes!
