### ISSUE TITLE
[FR] F# Language Support

### ISSUE THREAD

**Issue by aaron-jack-manning** [twibiral/obsidian-execute-code#178]
F# language support would be really nice, and shouldn't be too hard to implement given [F#'s features for scripting](https://learn.microsoft.com/en-us/dotnet/fsharp/tools/fsharp-interactive/), which would allow it to be done through the `dotnet` command line interface.

**Comment by twibiral** [comment]
Released in [1.6.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.6.0) :)

**Comment by mayurankv** [comment]
As far as I can see no listener is actually implemented for F# (indeed clicking the run button appears to do nothing). Furthermore the F sharp file extension setting appears to be unused for the F sharp executor. If this is the case, whilst the setting should remain for future compatibility, the option to change this should not show up under settings (and should be commented out). Apologies if I'm missing something!

**Comment by SasaCetkovic** [comment]
Has anyone managed to make this work?
