### ISSUE TITLE
Imports and Pre/Post in run- not working

### ISSUE THREAD

**Issue by WizzardMaker** [twibiral/obsidian-execute-code#179]
I am mostly working with the live preview editor, for fast development of small code snippets.

I tried using the {pre} and {label=''} + {import=['']}, but those don't seem to work for code blocks with the run- prefix - at least not for Haskell. Removing the run- and going to Preview mode works.

**Comment by twibiral** [comment]
Yes, at the moment it only works for the preview mode. This will be improved in the future, probably when #129 works

**Comment by twibiral** [comment]
Should be fixed with [version 1.9.1](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.9.1)
