### ISSUE TITLE
Magic @vault and @note start with `app://local/`

### ISSUE THREAD

**Issue by xmacex** [twibiral/obsidian-execute-code#181]
Hi, what a powerful extension – thank you!

I noticed that outputs of both the `@vault` and `@note` [magic commands](https://github.com/twibiral/obsidian-execute-code#magic-commands) are prepended by the string "`app://local/`", meaning they won't actually point to things on disk.

    ```python
    print(@vault)
    print(@note)
    ```

Gives me

    app://local//Users/myusername/Library/CloudStorage/GoogleDrive-myemailaddress/My Drive/notes
    app://local/a bunch of nice notes/a particularly fine note.md

I can grab their output into a string variable, and the `str.split('app://local/', 1)[1]` (or `str.removeprefix('app://local/')` on Python > 3.9) to prune it, but that seems like a workaround, given that the documentation for `@vault` and `@note` are "Inserts the vault path as string" and "Inserts the note path as string", respectively. Is this the intended behavious?

Thanks :)

**Comment by chlohal** [comment]
Hi! Seems like we need to improve that, yes. It seems that we also need to make the documentation more specific. Thank you for reporting!

**Comment by twibiral** [comment]
Hi @xmacex, I included the `app://local/` in front of the path because otherwise access to the file is sometimes denied in some programming languages (e.g. in JS or when adding new HTML to the note). Keeping the `app://local/` was no problem for me when I used it in python. But in python, I only used it to include new HTML, so maybe that's the problem.

I don't know exactly when, for what languages, and for what operating systems the `app://local/` is needed. I will look into this

**Comment by xmacex** [comment]
It is always nice and a learning opportunity to hear about design intent that went into things as they currently are. Thank you for sharing!

I also thought separate magics might be simplest and more versatile and allow for doing different things such as run the same code in Obsidian and in "normal" environment. I'd maybe call them `@vault_url` since it is one with the app scheme included, and `@vault_path` which would sound like a file path to me.

**Comment by twibiral** [comment]
You are right, changing it to `@vault/note_path` and `@vault/note_url` will be better. I will do this soon

**Comment by twibiral** [comment]
Released in [1.6.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.6.0) :)
