### ISSUE TITLE
Feature Request: Light/Dark Mode

### ISSUE THREAD

**Issue by mayurankv** [twibiral/obsidian-execute-code#187]
For visualisations, it makes sense to have different output (colour schemes) based on light or dark mode. Would it be possible to pass whether Obsidian is in light or dark mode as a magic parameter?

**Comment by chlohal** [comment]
Added! :)

**Comment by twibiral** [comment]
It will be released soon :)

**Comment by twibiral** [comment]
Released in [1.6.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.6.0) :)
