### ISSUE TITLE
support BAT files (batch script)

### ISSUE THREAD

**Issue by hannesdelbeke** [twibiral/obsidian-execute-code#190]
what's needed to add support for BAT files (batch script)?
(similar to powershell)

**Comment by twibiral** [comment]
You can execute them by changing the path settings in the menu for shell:

![grafik](https://user-images.githubusercontent.com/46483257/209585175-c99ef99c-4971-4342-9e55-7a69b7860a3b.png)

**Comment by twibiral** [comment]
We can of course also add a new batch language option 👍

**Comment by twibiral** [comment]
Released in [1.6.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.6.0) :)
