### ISSUE TITLE
magic command unexpected value

### ISSUE THREAD

**Issue by hannesdelbeke** [twibiral/obsidian-execute-code#191]
when trying the magic command in both powershell or shell (bash ships with git on windows)
```shell
echo @vault
```
it returns: `app://local/C:/Users/hanne/OneDrive/Documents/repos/obs_test`
when i expected just  `C:/Users/hanne/OneDrive/Documents/repos/obs_test`

is this on purpose, or a bug?

it causes issues when trying to browse to a directory 

```shell
cd @vault
```

tested on windows 11

**Comment by twibiral** [comment]
Hi @hannesdelbeke, this is on purpose but maybe it needs to be changed. I answered it in #181
