### ISSUE TITLE
New @vault_path magic causes syntax error

### ISSUE THREAD

**Issue by matthewturk** [twibiral/obsidian-execute-code#198]
Hi!  I'm using version 1.6.0.  I'm trying to use `@vault_path` in a Python block.  I have no python code injected, and I'm running a python 3.11 interpreter.  This block:

```
print(@vault_path)
```

inside a `run-python` block returns the following error:

```
invalid syntax. Perhaps you forgot a comma? (<code block>, line 4)
```

I'm still able to use `@vault`, but I was hoping to get the filesystem location (for `pyomd`) and keep forward compat, so I was using `@vault_path` instead.  I do get the same error when using `@vault_url`.

Thanks!

**Comment by matthewturk** [comment]
I apologize for the rapid update, but I just disabled notebook mode and have a bit more info -- the error seems to be that `@vault` is being grabbed and then `_path` concatenated, so it looks like:

```
print(@vault_path)
  File "/run/user/1000/app/md.obsidian.Obsidian/temp_1672247532329.py", line 4
    print("app://local//home/myuser/path/to/Vault"_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

**Comment by twibiral** [comment]
Hi, that was just a stupid mistake I could fix fast.  Thanks a lot for drawing my attention to it!

Update the plugin to the new version [1.6.1](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.6.1) and it should work.

If it works close the issue please, otherwise tell me what happened.

**Comment by matthewturk** [comment]
That did it!  Thank you so much for your quick response!
