### ISSUE TITLE
[FR] Save codeblock output as text within MD file?

### ISSUE THREAD

**Issue by kees-** [twibiral/obsidian-execute-code#209]
Hi, executing code is fantastic, but if the target of the Markdown file is to be displayed as a read-only page (ex: rendering to static HTML), an option to automatically retain the code output would be very useful.

Currently this is obviously very easy to do manually by copy pasting the output.

But, thinking how this could be accomplished!

- Additional palette command,
- block header argument,
- settings flag,

to run an individual block/all blocks, creating plain text blocks below themselves, each flagged as an `"out"` to not continuously dupe results?

I'm imagining a very interesting environment for code blogging dynamically :)

**Comment by chlohal** [comment]
This is currently a PR that I'm working on!! #129 I did it pretty much how you conceptualized it; I like the idea of a block header argument, though. Thanks!!

There are some issues with how Obsidian renders Markdown which we need to work out before merging that PR-- take a look at the PR page for more detail :)

Thank you for the issue!

**Comment by kees-** [comment]
Woops, I scrolled through the issues but didn't see it right there in the PRs. Great!

I'll leave this open ig at least until that PR merges. Plus I'd be pretty invested in this feature so I'll take a look and comment there if I try make some headway. Thx!

**Comment by twibiral** [comment]
Feature is now implemented by #384 and will be released soon.
