### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by Woile** [twibiral/obsidian-execute-code#21]
It would be awesome if this plugin supported `rust`. I have a lot of notes and samples that would like to run.
Looking at the code, it seems it should be possible. I think I could provide a PR somewhere in the future.

Thanks!

**Comment by pspiagicw** [comment]
Can we use `cargo-eval` for this purpose ? I yes I can start work on this.

**Comment by twibiral** [comment]
> Can we use `cargo-eval` for this purpose ? I yes I can start work on this.

`cargo-eval` executes Rust in a script like fashion, right? That would be perfect!

**Comment by twibiral** [comment]
Released in #50
