### ISSUE TITLE
The suppression of ANSI color markup does not work for uncaught exceptions.

### ISSUE THREAD

**Issue by ohthatwright** [twibiral/obsidian-execute-code#212]
Powershell version: 7.3.1
Windows: 11 Pro Version 22H2 Build 22621.1105
Obsidian: 1.1.12
Obsidian Execute Code: 1.6.2

# Summary
When a Powershell code block using Obsidian Execute Code throws an uncaught exception, the regular mechanisms for suppressing ANSI color markup are bypassed (perhaps because the uncaught exception busts out to a place where the environment variables used for suppression of ANSI color markup are set differently?). I think this is a difficult edge case and maybe is not meant to be handled or contained. I think one would have to take the output streams (error stream?) from the completed process and filter them to fix this (that's a guess).

# Code block where the final use case (#4) throws an uncaught exception.
Here is the code block that shows this in case #4, the uncaught exception. (See further below for image of this code block and its result).
```Powershell
Write-Output "1. Show value for `$PSStyle.OutputRendering used in obsidian-execute-code"
Write-Output "`$PSStyle.OutputRendering: $($PSStyle.OutputRendering)"

Write-Output "`n2. Show regular output in obsidian-execute-code: No Color (by design--Plaintext). NOTE: In a regular Powershell shell, this would get a colored header for the table."
Get-Process | Select-Object -First 1 | Format-Table

Write-Output "`n3. Show that caught exception is regular in obsidian-execute-code: No Color (by design--Plaintext)."
try
{
	throw "Exception that is caught"
}
catch
{
	Write-Output $_.Exception.Message
}

Write-Output "`n4. Show that uncaught exceptions ecape containment attempts, with ANSI color codes coming through"
throw "Exception that is uncaught"
```
# Image showing result of running code block
![UncaughtExceptionsLeakAnsiColorCoding](https://user-images.githubusercontent.com/118786606/213350812-302de6ab-5a3f-484d-9191-2ded88d2f146.png)

**Comment by chlohal** [comment]
Interesting; thanks! I think that we handle ANSI on the `stdout` stream, but not the `stderr` stream, and that's why this error occurs.

**Comment by twibiral** [comment]
Should work now with [Release 1.7.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.7.0).
