### ISSUE TITLE
Unable to run rust code block

### ISSUE THREAD

**Issue by hthuong09** [twibiral/obsidian-execute-code#214]
Hi,  thanks for an awesome plugin.
I'm just setting up this plugin today and facing an issue with running Rust code blocks.
I'm getting this error

<img width="718" alt="image" src="https://user-images.githubusercontent.com/8191266/213988661-870cda4f-0e7b-4f01-baea-a8ca6b4ad146.png">

I have cargo and cargo eval installed
<img width="276" alt="image" src="https://user-images.githubusercontent.com/8191266/213989416-4e2982f7-f411-4133-86c0-2a91b032ced6.png">

I also set cargo path correctly in Obsidian settings
<img width="860" alt="image" src="https://user-images.githubusercontent.com/8191266/213989691-a77229cb-f3d8-464b-afe4-0aef801037ba.png">

Here is my Obsidian debug info
```
SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.1.9
	Operating system: Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 22.2.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Prism v3.2.0
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 16
	Plugins enabled: 14
		1: Dataview v0.5.55
		2: Emoji Shortcodes v2.2.0
		3: Obsidian Git v2.16.0
		4: Auto Link Title v1.4.1
		5: Calendar v1.5.10
		6: Paste URL into selection v1.7.0
		7: Style Settings v0.4.12
		8: Templater v1.16.0
		9: QuickAdd v0.8.0
		10: Advanced Tables v0.18.1
		11: Periodic Notes v0.0.17
		12: Checklist v2.2.12
		13: Tracker v1.10.9
		14: Execute Code v1.6.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

Any idea why this happens?

**Comment by hthuong09** [comment]
I also tried to debug a bit but not sure what happened. Here are my findings:
- The settings are correct, and we're able to generate the correct args for `spawm`
<img width="541" alt="image" src="https://user-images.githubusercontent.com/8191266/213992238-ba92b05e-8117-4896-a3f1-e951b7bac0c0.png">

- The file exists at the correct path as well, but the process fails to execute. I have tried to execute the exact same command by creating and js file and executing with node and it runs correctly.
- I tried to hard code `tempFileName` to an existing file and it run correctly but with the automatically created file, it is not working.

**Comment by chlohal** [comment]
Interesting! Thank you for your debugging steps!

When the `spawn` breakpoint is triggered, could you open the temp file & see if it has the proper content?

**Comment by hthuong09** [comment]
@chlohal Yes, it had proper content and I was able to run it with `cargo eval file_path.rs` in my terminal.

After futher investigation, I had another interesting finding. It was able to execute correctly once I manually executed the file once in terminal before `spawn` is called.

It makes me think that maybe something is wrong with cargo itself? I tried to remove the version I installed via homebrew and using the command on rustup.rs to install. Somehow the version I installed using rustup worked.

I'll close this issue for now and suggest anyone who have this issue, you might want to try https://rustup.rs/ instead of homebrew.

**Comment by twibiral** [comment]
On Linux there is a similar problem when you install a package via snap. Very funky

**Comment by chlohal** [comment]
*interesting.* Thanks!

> It was able to execute correctly once I manually executed the file once in terminal before spawn is called.

This makes me wonder whether it's some sort of MacOS security feature? I'm glad you found a solution! :)

**Comment by 12to-the12** [comment]
I'm having the same problem with the flatpak on Fedora

`error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `temp_1682266808259` due to previous error
internal error: cargo failed with status 101`
