### ISSUE TITLE
interesting UX issue worth mentioning in the README

### ISSUE THREAD

**Issue by hannesdelbeke** [twibiral/obsidian-execute-code#221]
when running a batch command, it sometimes behaves different compared to running the same batch command in a BAT file.

e.g. variables need to be `%%A` in the BAT file, but `%A` in the command

when we run execute code, we execute the "command". or at least that's what I thought.
But for my code to execute correctly, I need to use the code that works in the BAT file. Not the command. so `%%` isntead of `%`

**Comment by chlohal** [comment]
Interesting! I think that a different mental model is at fault -- I agree that this should be documented under the shell section.
