### ISSUE TITLE
I can't export results to PDF

### ISSUE THREAD

**Issue by SAGA-0** [twibiral/obsidian-execute-code#224]
Sorry, this is my first time using this plugin, and I have some problems that cannot be solved. 
I can run the code and view the results normally on the preview page, but the results cannot be displayed when exporting to PDF.
Did I ignore some settings?

**Comment by twibiral** [comment]
Hi @SAGA-0 , at the moment it is impossible to store the output in the PDF as it isn't included in the markdown file. We are already working on this, see #209 and #129

**Comment by twibiral** [comment]
Feature is now implemented by #384 and will be released soon.
