### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by JCzz** [twibiral/obsidian-execute-code#231]
If I add a shell code to be executed:
```shell
echo $PATH
```

It do not print the same $PATH as if I run the same command in macos terminal.

Update: This seems to be working on Windows

Do you know why?

**Comment by JCzz** [comment]
For now I found that I can add to settings "shell/Inject Shell code":

`export PATH=$PATH:/opt/homebrew/bin`

**Comment by twibiral** [comment]
Hi @JCzz PATH variables are not included at the moment, as discussed in #37

**Comment by JCzz** [comment]
Hi @twibiral 

Ok, thanks for info! 👍
