### ISSUE TITLE
Possible accent error in Python run

### ISSUE THREAD

**Issue by LucasLauri** [twibiral/obsidian-execute-code#246]
Hello, I'm trying to run a simple code to run through some files in a specific folder with this code:

```
import os
import pathlib  

print("---START---")

folderPath = "G:\\Meu Drive\\Obsidian Vaults\\Lauri's Vault\\600 Calendário\\Test"
print(folderPath)

for path, subdirs, files in os.walk(folderPath):
	for name in files:
		print(pathlib.PurePath(path, name))

print("---END---")
```

If I run this with this Obsidian plugin it seems me that no file is returned:
![image](https://user-images.githubusercontent.com/69014787/233784610-7e21503b-af6d-4d9f-8c2a-d35a431715c9.png)

But if i run it in Visual Code it runs normally:
![image](https://user-images.githubusercontent.com/69014787/233784602-1ec33c7b-5418-4c2b-9ab6-182d363bcdbc.png)

Another thing, if I run the same code with `folderPath = "G:\\Meu Drive\\Obsidian Vaults\\Lauri's Vault"` it woks OK in obsidian, maybe there is something with the accent in "600 Calendário"?

My plugins settings is:
![image](https://user-images.githubusercontent.com/69014787/233785024-511a5e09-ba6f-48a5-9e46-4e8525503053.png)

And my OS is Windows 10 if it helps.

**Comment by hvitis** [comment]
@LucasLauri 

Try changing the Notebook mode. If not, then try running python in terminal:
`
>>> import os
>>> import sys
>>> os.path.dirname(sys.executable)
'C:\\Python25'
`
And update your Python path.

**Comment by LucasLauri** [comment]
@hvitis Disabling the Notebook mode and then close and open Obsidian worked!

Thanks :)
