### ISSUE TITLE
Racket run button does nothing

### ISSUE THREAD

**Issue by joaogui1** [twibiral/obsidian-execute-code#254]
Hi! 
While Python is working I seem to be unable to get racket working
<img width="679" alt="image" src="https://github.com/twibiral/obsidian-execute-code/assets/13261989/0ab21570-5497-45b4-bad9-c89e41a6a2fd">
I'm on MacOS and I set the racket path to `/Applications/Racket v8.7/bin/racket`, which is what I get when I run `which racket`

**Comment by mayurankv** [comment]
The listener for racket appears not to have been added yet.

**Comment by twibiral** [comment]
Fixed in [Version 1.9.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.9.0)
