### ISSUE TITLE
R plots not displaying

### ISSUE THREAD

**Issue by dominicwhite** [twibiral/obsidian-execute-code#256]
I am not able to get R plots to display below the code block that created them, for example:

![Screenshot from 2023-05-21 14-30-00](https://github.com/twibiral/obsidian-execute-code/assets/6020835/76e447ba-7b39-4dbc-a2aa-c75d40e1482f)

However, I was able to verify that the corresponding image file output is being created, and stored in my `/tmp` folder:

![Screenshot from 2023-05-21 14-25-39](https://github.com/twibiral/obsidian-execute-code/assets/6020835/56f147cb-dadc-4c67-9d9f-1bc645020281)

Any idea why the plugin or Obsidian cannot seem to find these files to embed in the actual document?

Regular R code (without plots) runs fine and displays output text. I have tried toggling the plugins various R settings on and off (e.g. notebook mode) and restarting Obsidian, but I have not been able to fix the plot issue. 

For reference, this is with Rscript v 4.1.2, Obsidian v1.2.8, and Execute Code v1.8.1, all running on PopOS (i.e. Ubuntu) 22.04.

**Comment by mayurankv** [comment]
This is also an issue for octave plots. It's a result of app:// links no longer working for `<img>` tags.

**Comment by mayurankv** [comment]
This is documented at the [v1.2.8 release notes](https://forum.obsidian.md/t/obsidian-release-v1-2-8/59086).

**Comment by twibiral** [comment]
Fixed in [Version 1.9.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.9.0)
