### ISSUE TITLE
Output or Results Does Not Persist 

### ISSUE THREAD

**Issue by JeromeWYCB** [twibiral/obsidian-execute-code#259]
The output from my Python code is cleared automatically once I switch to work on another note. Is this the expected behavior?

**Comment by kguidonimartins** [comment]
Is there a way to make the output persistent?

**Comment by twibiral** [comment]
The output is just added to the html you are looking at in the moment. There is a PR where we tried to improve this and save the output in another file: #129 

But we never finished it

**Comment by Borillion** [comment]
Would appreciate if this was implemented ;)

**Comment by twibiral** [comment]
Feature is now implemented by #384 and will be released soon.
