### ISSUE TITLE
[FR] Applescript support

### ISSUE THREAD

**Issue by mayurankv** [twibiral/obsidian-execute-code#261]
Would it also be possible to add applescript support? 

Applescript files end in `.scpt` and are called from commandline via `osascript /path/.../file.scpt`.
Alternatively single line (possibly multiline?) statements can be called directly using `osascript -e '<statement>'`

As far as I am aware there is no REPL environment for applescript.

Please let me know if I can add anything else to make this easier!

**Comment by mayurankv** [comment]
And sorry, just to double check, if I were to try and make these changes myself and submit them as a pr, would I only need to make the relevant changes to `main.ts`?

**Comment by hannesdelbeke** [comment]
you can use this PR as reference https://github.com/twibiral/obsidian-execute-code/pull/193/files#diff-f2a4304d75490ee308ba20fc72fedeeadda5cee948e3fa1ead4b363e63a13025

**Comment by twibiral** [comment]
Added in [Version 1.9.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.9.0)
