### ISSUE TITLE
[FR] PHP support

### ISSUE THREAD

**Issue by tlwt** [twibiral/obsidian-execute-code#263]
to add to the other feature request: PHP support would be great.

**Comment by hannesdelbeke** [comment]
if anyone is interested in adding this, you can use this PR as reference https://github.com/twibiral/obsidian-execute-code/pull/193/files#diff-f2a4304d75490ee308ba20fc72fedeeadda5cee948e3fa1ead4b363e63a13025

**Comment by tlwt** [comment]
@hannesdelbeke - I finally managed to take a look at this and implement similar changes. Once I compile the plugin on Mac I get the following errors: `Could not open input file: /var/folders/mc/tr50w1s94cb27zw9_zfpcn_40000gn/Ttemp_1713273012350.php`

And same happens for other languages, so something else seems to be broken. The changes are currently committed to my fork. Could you or @twibiral have a look at: https://github.com/twibiral/obsidian-execute-code/compare/master...tlwt:obsidian-execute-code:master

**Comment by hannesdelbeke** [comment]
i don't use PHP anymore so wont have time to work on this.

**Comment by tlwt** [comment]
Sorry for not being specific enough - PHP works with the existing plugin when I use the ruby configuration section and enter the PHP binary path. 

After doing the changes and compiling the plugin neither RUBY nor PHP work anymore and fail with the error messages above. I dont think any debugging is needed in terms of PHP - I think I just fail in properly compiling the plugin.

**Comment by twibiral** [comment]
It's finally released with version [2.0.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/2.0.0). Sorry for needing so long.
