### ISSUE TITLE
Jupyter Notebook plugin for Obsidian project: obsidian-jupyter

### ISSUE THREAD

**Issue by NumesSanguis** [twibiral/obsidian-execute-code#27]
Hi,

In case you haven't come across it, there is an Obsidian plugin for Jupyter Notebook style execution:
https://github.com/tillahoffmann/obsidian-jupyter
Maybe it can inspire this project? Never tried it, so can't vouch for it.
Hope it somehow can inspire this project ^^

I'm just reading about all kinds of possibilities with Obsidian and am also interested adding interactive code to my Vault (that works on mobile as well).

**Comment by twibiral** [comment]
Hi, thats already on the list of future improvements.
