### ISSUE TITLE
Fortran support

### ISSUE THREAD

**Issue by redscorpse** [twibiral/obsidian-execute-code#270]
Allow Fortran support and any other language (allow user configuration) like [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) on VSCode.

**Comment by hannesdelbeke** [comment]
if anyone is interested in adding this new language, this PR makes a great reference for adding a new language https://github.com/twibiral/obsidian-execute-code/pull/193/files#diff-f2a4304d75490ee308ba20fc72fedeeadda5cee948e3fa1ead4b363e63a13025
