### ISSUE TITLE
matplotlib svg embed error (insider v0.15.2)

### ISSUE THREAD

**Issue by h0uter** [twibiral/obsidian-execute-code#28]
Hi thanks for the awesome plugin!

I get the following error when checking the option to embed the "Embed Python Plots" on the latest insider obsidian build (v0.15.2)
I read they changed a bunch of things with codemirror behind the scenes so perhaps it's relevant for you!

<img width="770" alt="image" src="https://user-images.githubusercontent.com/40892865/174558454-086094b8-f75a-4d2d-abac-76cfca4373a4.png">

**Comment by twibiral** [comment]
Thank you for creating this issue. I think I found the bug. Try adding `;` after `plt.show()` as a quick fix until I create a new release.

**Comment by twibiral** [comment]
Solved by #29
