### ISSUE TITLE
Cannot run java code 

### ISSUE THREAD

**Issue by Emporio-a** [twibiral/obsidian-execute-code#304]
<img width="549" alt="image" src="https://github.com/twibiral/obsidian-execute-code/assets/55417023/6536adc6-b728-4a6d-b6a0-192a3c48416b">
I'm new to java. Maybe my java path is wrong. Can anybody tell me where is the location of java path? Is it the file named "java.exe"?

**Comment by Emporio-a** [comment]
<img width="180" alt="image" src="https://github.com/twibiral/obsidian-execute-code/assets/55417023/a3f74284-2a62-4d8d-9dc8-ecd728bf09f2">
Here is the path I'm recently using.

**Comment by twibiral** [comment]
I think there is something wrong with the spaces before the main function. Try this: 

```java
public class HelloWorld{
public static void main(String[] args){
System.out.println("Hello World");
}
}
```

**Comment by Emporio-a** [comment]
> I think there is something wrong with the spaces before the main function. Try this:
> 
> ```java
> public class HelloWorld{
> public static void main(String[] args){
> System.out.println("Hello World");
> }
> }
> ```

Thank you！I really appreciate the job you have done！
