### ISSUE TITLE
run javascript code blocked

### ISSUE THREAD

**Issue by wuxiongliu1** [twibiral/obsidian-execute-code#322]
node version:  v16.20.2
obsidian version: v1.5.3

I run the javascript example ,but it seems blocked , the console print error.
<img width="1439" alt="image" src="https://github.com/twibiral/obsidian-execute-code/assets/5119063/37140b33-046b-4d96-afb4-5961cfff0348">

**Comment by twibiral** [comment]
Can you please specify operating system, node.js version, Obsidian version, and teh plugin version? Does the problem also occur when you disable the notebook mode in the settings?

**Comment by wuxiongliu1** [comment]
thanks for reply;

node version: v16.20.2
obsidian version: v1.5.3
os: mac os monterey  12.2.1

plugin version: 1.10.0
----------------------------

When I disable the notebook mode,  I can run the javascript code correctly. thanks a lot.🌹🌹🌹
