### ISSUE TITLE
[BUG] Version 1.11.0 was not built correctly (and a small typo in the readme)

### ISSUE THREAD

**Issue by hellocharli** [twibiral/obsidian-execute-code#343]
**Describe the bug**
The built main.js and manifest.json in release 1.11.0 and 1.10.0 are 100% identical.

**Software Version**
macOS 14.5
Obsidian 1.5.12

**To Reproduce**
1. Install the plugin from the obsidian plugin browser
2. Click the settings for the execute code plugin
3. Try to find Swift or Ocaml language settings

**Expected behavior**
Features from the 1.11.0 release

**Screenshots**
<img width="929" alt="image" src="https://github.com/twibiral/obsidian-execute-code/assets/111490544/ed596cbe-6faf-48ba-89c2-7f6c8ed262c6">

**Additional context**
Line 462 of README.md needs to be a newline with {```} to close the ocaml code block.

**Comment by twibiral** [comment]
Thank you for reporting this! I will look into it over the weekend. The OCML settings are in the settings file, so hopefully I just copied the wrong main.js

(Related to #340)
