### ISSUE TITLE
[BUG] seemingly trying to use \ on linux instead of / when executing something in /tmp

### ISSUE THREAD

**Issue by AkashicLibrary** [twibiral/obsidian-execute-code#345]
**Describe the bug**
It seems that when trying to execute any language that needs to be compiled first (Python works because it doesn't need to compile from my knowledge) it is trying to access the compiled file like this /tmp\(temp file number).(compiled file ending) which results in an EACCES Permission denied.

**Software Version**
OS: Archcraft x86_64,
Plugin Version: 1.11.1
Obsidian Version: 1.5.12-1 **Edit**: downloaded from the arch extra repo

**To Reproduce**
1. create a codeblock for any compiling language like rust or java (in my example I used java)
2. specify run-(chosen language)
3. write simple hello world the way it works with compiler normally
4. press run
5. see Error while executing /usr/bin/java -ea /tmp\temp_1714979553374.java: Error: EACCES: permission denied, open '/tmp\temp_1714979553374.java'

**Expected behavior**
It should output hello world just like it does in python.

**Screenshots**
![error](https://github.com/twibiral/obsidian-execute-code/assets/146709486/5d7cc531-99b2-4b2a-a45a-05326177f3ee)

**Additional context**
if I'm just stupid and set it up wrong please inform me of it. Because I do not quite understand if this is a bug or if I did something wrong.
Sorry for any grammatically wrong sentences, English isn't my first language

**Update**
thanks to @He-Zu a fix was found. Thank you very much!

**Comment by SanteIsHere** [comment]
I am also encountering this issue.

**Comment by DilicalFlame** [comment]
![image](https://github.com/twibiral/obsidian-execute-code/assets/88958490/628917c1-6e84-44a3-9d84-76d2958dd283)
same happening in c-programming, is there any temporary workaround?

**Comment by He-Zu** [comment]
make this change in main.js
![grafik](https://github.com/twibiral/obsidian-execute-code/assets/116963345/b3242a24-04e1-4fd5-b9de-c899185763d0)
to 
![grafik](https://github.com/twibiral/obsidian-execute-code/assets/116963345/19c593d4-7730-4fa8-9905-3439990b96c7)
then it works for me

**Comment by apolzek** [comment]
I am also encountering this issue.

**Comment by RileyLeff** [comment]
Thank you @He-Zu 🙏

**Comment by bweinand** [comment]
@He-Zu You made my day! Thank you 🙏

**Comment by AkashicLibrary** [comment]
@He-Zu Thank you this worked.

**Comment by nfiles** [comment]
Haha I didn't notice this issue until now. I submitted a PR that should fix the same problem against issue #347

**Comment by twibiral** [comment]
Fixed with new release [version 1.12.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.12.0)
