### ISSUE TITLE
[BUG] Racket cannot find temporary code file

### ISSUE THREAD

**Issue by wtaverni** [twibiral/obsidian-execute-code#346]
When executing code using Racket, I get the following error message on macOS (M1), using Racket v8.12:

`open-input-file: cannot open module file
  module path: #<path:/var/folders/sf/qh13w2p14sv2vmggf929wwq80000gn/Ttemp_1715066408500.rkt>
  path: /var/folders/sf/qh13w2p14sv2vmggf929wwq80000gn/Ttemp_1715066408500.rkt
  system error: no such file or directory; rkt_err=3`

**Comment by nfiles** [comment]
I'm not familiar with Racket, but it sounds like this has the same root cause as #347

**Comment by twibiral** [comment]
Should be fixed with new release [version 1.12.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.12.0). Ping me if the new release doesn't solve the problem.
