### ISSUE TITLE
Failed to load some notes after updating

### ISSUE THREAD

**Issue by verroust** [twibiral/obsidian-execute-code#35]
Hello, I have a problem after updating to the latest version.
The message is: "_Failed to load diagrams.md notes
Cannot read properties of null (reading 'vaultpath')_"
There is no code in these notes 
Everything is ok when I disable the plugin.

Environment
OS Windows 11 (21H2)
Obsidian Version : 0.15.9

**Comment by twibiral** [comment]
Are there inline code snippets of tables in these notes?

**Comment by twibiral** [comment]
Solved in Release [0.10.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/0.10.0). 

Do not hesitate to reopen this issue or open another one if more problems occur.
