### ISSUE TITLE
[BUG] Code blocks not working

### ISSUE THREAD

**Issue by Kamek437** [twibiral/obsidian-execute-code#362]
I just installed obsidian and this plugin on windows 11 and I canno't get the code to run, no run button like in the pics, and there is no output when I hit run all code blocks. Is there some special way to get this to function? I'm just inserting new code blocks but also tried the three backticks way. I have node installed and pythong both functioning well and available from command line. 

Windows 11, latest patches. Obsidian latest version. Python 3.10, Node v20.14.0.

Install everything like normal and try to run a simple hello world block.

Code block should run and output something OR give an error message with more info.

![Screenshot 2024-06-11 133452](https://github.com/twibiral/obsidian-execute-code/assets/85422028/0a69a5ca-86ed-4cca-9d2d-84099fec265d)
 Am I doing something wrong? In theory it should just work but I'm new to Obsidian and don't know where to find the logs. It should give some sort of error if it doesn't work though.

**Comment by twibiral** [comment]
You need to add the language name to the code block, like this:

````
```python
print("Hello World")
```
````

**Comment by Kamek437** [comment]
I feel stupid now. Thank you.

**Comment by Kamek437** [comment]
In the top bar isn't there supposed to be a button to run the code? It doesn't show up for me.

**Comment by Kamek437** [comment]
I tried you're marking the code type but no change. Where can I see the output of the extensions? Or a log file or something I can check? It isn't loading correctly I think because the button didn't show up in the top bar.

**Comment by twibiral** [comment]
The run button will only appear when you view it in rendered mode (you can switch to the rendered mode using this button in the lower right corner: 
![image](https://github.com/twibiral/obsidian-execute-code/assets/46483257/bb7aa317-e7b8-42d9-9346-dc29a46c7a4d)

**Comment by Kamek437** [comment]
Thank you, I feel stupid.

**Comment by twibiral** [comment]
Don't worry ^^
