### ISSUE TITLE
[BUG] Add example of creating a runnable code block to the readme

### ISSUE THREAD

**Issue by brainbicycle** [twibiral/obsidian-execute-code#383]
**Describe the bug**

This is a very cool plugin, thanks for making it! I downloaded it created a typical codeblock with three backticks and pasted one of the code examples into it and was confused why I couldn't run anything. Only after some google around I realized I need `run-javascript` as part of the code block to make it runnable. I think it would be great to have a workable example in the readme.

**Comment by twibiral** [comment]
In the readme is a video demonstrating that basic code blocks do not work in preview mode, that you need to switch to the rendered mode to run them. Also, further down in the readme, there is an explanation for how to use the `run-` prefix to run code blocks in the preview mode.

I will add a short quickstart guide.
