### ISSUE TITLE
support numpy

### ISSUE THREAD

**Issue by weivdev** [twibiral/obsidian-execute-code#39]
numpy as a very popular python package is not supported.

```run-python
import numpy as np
a = np.random.rand(10)
b = np.random.rand(10)
c = np.dot(a, b)
```

I have number pip installed and then run above script and set the python path to be where my python was installed:
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3

however when run this script, i saw error on Traceback (most recent call last), such error does not exist outside of obsidian, and i have tried uninstall/install numpy serveral times but no magic:

```
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/Library/Frameworks/Python.framework/Versions/3.10/bin/python3"
  * The NumPy version is: "1.23.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

**Comment by twibiral** [comment]
Numpy normally works fine in combination with the plugin. Seems to be another issue. Maybe try setting up a new environment (virtenv / anaconda / ...) in python and change the path accordingly.

**Comment by weivdev** [comment]
Thank you for the hint, yes it works after installing anaconda and set the python to be for example: /Users/myusername/opt/anaconda3/bin/python

This plugin works well for numpy then. Will close this issue.
