### ISSUE TITLE
Rust support 

### ISSUE THREAD

**Issue by lifefir3** [twibiral/obsidian-execute-code#40]
I been using your plugin for python and it works great, how you kindly add Rust support ?

**Comment by twibiral** [comment]
I will add it to future work. I don't have experience with Rust, so it will likely need some time.

If you are more experienced in Rust and have some experience in TypeScript/JavaScript please feel free to implement it by yourself and create a pull request.

**Comment by twibiral** [comment]
Duplicate (see #21)
