### ISSUE TITLE
Inline code error inside tables

### ISSUE THREAD

**Issue by pegajoso** [twibiral/obsidian-execute-code#41]
Inline code (single backticks) does not work inside tables. Switching to another file and then switching back will fail to open the file and produce the notice `Failed to load "Lorem Ipsum.md". Cannot read properties of null (reading 'vaultPath')`.

**Comment by twibiral** [comment]
This plugin doesn't interact with inline code. Try disabling the plugin and try again. If the error persists this plugin has no relevance for the error.

If you are sure that this plugin is at fault please give me more information. Otherwise close the issue.

**Comment by twibiral** [comment]
I will look into this. The plugin shouldn't interact with inline code.

**Comment by twibiral** [comment]
Solved in Release [0.10.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/0.10.0). 

Do not hesitate to reopen this issue or open another one if more problems occur.
