### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by pspiagicw** [twibiral/obsidian-execute-code#42]
Hi, It would be awesome if Golang support is added. I may look into integrating it myself, but I have limited experience in TypeScript/Javascript.

**Comment by twibiral** [comment]
I will add it to the list of languages to support in future updates.

You can try to implement it and I can help you if you want. Otherwise I will implement it as soon as possible.

**Comment by pspiagicw** [comment]
Opened a PR #46 for this issue.

**Comment by twibiral** [comment]
Published in release [0.12.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/0.12.0)
