### ISSUE TITLE
Cannot execute Javascript using path returned from "which node" 

### ISSUE THREAD

**Issue by hdbham** [twibiral/obsidian-execute-code#43]
Python works fine, but having issues executing node using either zsh or bash. Have tried adding arguments, but to no avail. Is there something I might be missing?

**Comment by twibiral** [comment]
Are you trying to execute Node from a JavaScript code block or from a shell code block?

Post a minimal working example of the bug so I can understand what's going wrong, please.

**Comment by hdbham** [comment]
Disabled all other community plugins for this:
javascript code block tagged ```javascript {code here} ``` and node path set correctly.

![image](https://user-images.githubusercontent.com/13264116/186766725-0b6f1862-377d-45db-8f38-dfc763253e7a.png)

**Comment by hdbham** [comment]
Was navigating via keyboard and accidentally closed, reopening.
Thank you for your attention on this

**Comment by twibiral** [comment]
I made some changes in Release [0.10.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/0.10.0). Does this problem still occur?

**Comment by hdbham** [comment]
### got it working :+1: 
It's hard to say how or why, there's the possibility that the update may have helped. It may be another issue I was experiencing.

I should have remembered this sooner, I was executing via an integrated .appimage  ([TheAssassin/AppImageLauncher)](https://github.com/TheAssassin/AppImageLauncher), this may or may not have been the cause, but a reinstall helped resolve the issue, even reintegrated the new AppImage -- which was the same Obsidian version -- and it's working great! :+1: 

## Tests:
- Updating the add-on itself (did nothing) :x: 
- reinstall Obsidian .AppImage (add-on working!) :heavy_check_mark: 
- reintegrate .AppImage through same means (add-on still working) :heavy_check_mark: 

## Conclusion
- Latest update works
- Rebuild of same version resolves issue
- Integrated .AppImages should work
