### ISSUE TITLE
Haskell language support

### ISSUE THREAD

**Issue by jarikmarwede** [twibiral/obsidian-execute-code#76]
Hey,
I would like this plugin to have support for [Haskell](https://www.haskell.org/) if more languages can be added.

**Comment by twibiral** [comment]
Sure, this will be no problem. I will add it as soon as I am free.

**Comment by jarikmarwede** [comment]
It seems like the option for Haskell has been added with #99 
However it currently does not work on my machine. While running the code I get: "/bin/sh: 1: ghci: not found" even though ghci is accessible on the terminal and included in the PATH. Am I missing something?
I have even tried running it from "sh" and that works too.

**Comment by chlohal** [comment]
Hi! Thank you :) What OS are you using? If you're using Linux and Snap/AppImage/Flatpak, then Obsidian is running in a self-contained environment and won't be able to access your system's installation of ghci. There is a fix for this (installing the `.deb` version from Obsidian's website).

If you are not using Linux, then could you please try using the absolute path? 
To get the absolute path, you can run `which ghci`; then, in the plugin's settings, enter it for the "Ghci path" field.

I hope that this could help!

**Comment by jarikmarwede** [comment]
Thanks for the help. It works now after installing it using the `.deb` file. I also had to install ghci through apt though. I previously used ghcup but that somehow didn't get picked up.
Should the issue be closed now?

**Comment by chlohal** [comment]
Yep! I think that the issue can be closed.

I've authored a PR for adding this to the Known Issues section of the README, so that people can be aware of it in the future. Thank you very much for your help with that!
