### ISSUE TITLE
On windows, "\" are replaced with "/" in option paths and snippet do not run

### ISSUE THREAD

**Issue by sergeBoisse** [twibiral/obsidian-execute-code#77]
Windows-only bug : 
If you try to enter a path with backslashes in the plugin options, and then close the option panel and reopen it, then "\\" are systematically replaced with "/" .
Therefore the run button will trigger an ENOENT error on javascript or python snippets because the windows executable (resp.  node.js and python)  is not found.

The workaround is to edit the file data.json and replace "/" with "\". Then it works. But this should not be necessary.

**Comment by twibiral** [comment]
They are not replaced by accident, but as part of our process to sanitize paths. I did not notice this causes an issue on windows.

As I understand it, the plugin changes your paths from `User\\path\\to\\somewhere` to ``User//path//to//somewhere` which causes the problems?

**Comment by sergeBoisse** [comment]
Actually the problem was only after 1st installation of the plugin. I entered the python and node paths using the option panel (like C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Node.js and C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\python.exe),  then I I created a new md note and tried to run a javascript  snippet with the "run" button. I got the ENOENT  error.
I opened <vault path>\.obsidian\plugins\execute-code\data.json in notepad++, and found that backslashes had been replaced with slashes.  So I replaced with back slashes and was able to run the snippets.
The fun thing is, one day  later,  I ccheked  data.json again and discovered that all path had diseapeared, that is, i.e the value for node -path was "node" as if I had not entered any option. AND it still works ! I do not understand why but it works. I was not able to reproduce the error. So maybe you could consider this case closed.
Thank you anyway for this amazing plugin.

**Comment by twibiral** [comment]
Fixed with release [0.18.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/0.18.0).

The problem had nothing to do with the changed slashes and they are still changed while sanitizing the path.
