### ISSUE TITLE
Can't run Rust

### ISSUE THREAD

**Issue by afonsofrancof** [twibiral/obsidian-execute-code#81]
I get this error every time I try to run Rust code.
`error: could not find Cargo.toml in /home/user or any parent directory`
My cargo path is set in the settings.
I think this might be looking for a Rust project where one doesn't exist.

**Comment by RustyCobalt36** [comment]
Same problem, can also get the error if the cargo folder isn't right (_or is_)

`Error: spawn C:/cargopath  ENOENT`

**Comment by afonsofrancof** [comment]
> Same problem, can also get the error if the cargo folder isn't right (_or is_)
> 

You should be pointing it to the cargo executable , not it's folder.

**Comment by twibiral** [comment]
Fixed with release [0.18.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/0.18.0).
