### ISSUE TITLE
Update to version 1.0.0

### ISSUE THREAD

**Issue by twibiral** [twibiral/obsidian-execute-code#99]
@chlohal @milan338 I tried to merge all PRs and get them running. For me, the current version in `develop` is working great. Could you both test it on your machine to make sure it works?

 Could you also check the changelog to make sure I mentioned all the new features and changes, please?

I think the features you added matured this plugin greatly and it is time to publish version 1.0.0 based on the current version in `develop`.

The new release would solve #10 , #62 , #76  , #92 , and #96

**Comment by milan338** [comment]
Before bumping, I took a look and couldn't see the changes from #98 reflected in main.ts.

**Comment by milan338** [comment]
The toggle to disable input in code blocks also doesn't seem to work on my end, inputs still show up if the toggle is disabled. The delay to show the input box is a bit long. If the delay is decreased, would it still fix #96?

**Comment by chlohal** [comment]
Running Prolog now shows the input for me

**Comment by twibiral** [comment]
When I compare #97 to develop via the compare tool of my IDE their code looks exactly the same (except for some minor changes I made). Same for #98.

What do you miss? Did you look into the current version of develop or an older one?

**Comment by chlohal** [comment]
I'm on commit `c738c4d203a0d299fa0c7768a14862d9d91f26ca`, which appears to be the tip of develop for me. Looking through Github's web interface, main.ts seems like it doesn't have #97 or #98's changes: <https://github.com/twibiral/obsidian-execute-code/blob/develop/src/main.ts>.

Is everything pushed? Is there anything that we can do to checkout the right branch?

**Comment by twibiral** [comment]
You're right, I saw the missing changes now. Something has gone utterly wrong while merging, I am sorry...

I will look into this at the weekend. You can try to create a new PR that merges your changes into develop if you can.

**Comment by twibiral** [comment]
@chlohal @milan338 I invited you both as collaborators for this repository. This gives you more rights and hopefully helps to resolve this issue faster. You both contributed a lot to this project and I am very thankful.

**Comment by chlohal** [comment]
Thank *you!* I appreciate the invitation a lot :)

I hope that it's possible to fix the merging. I will make a new PR soon to fix `main.ts`, but please feel free to revert it if you're able to correct the merge. I'm sorry.

**Comment by twibiral** [comment]
Everything seems to work now and I released the update :)
